### ISSUE TITLE
Unhandled Exception after kyber DAI swap

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-wizard#207]
Version: git HEAD d04d768532fbdd2b55c356b31aeb99d0f1f418d8

```
2020-05-13 11:24.52 Redirecting to /swap/config-0xf3933ff73F1b4C7A94AD663f75CfDC2f338f9463-mainnet.toml/DAI
2020-05-13 11:25.02 Starting swap at Kyber
2020-05-13 11:25.02 calculating exchange rate
2020-05-13 11:25.02 calculating gas price
2020-05-13 11:25.03 estimating gas
2020-05-13 11:25.05 Gas Limit                      gas_with_margin=548997 max_gas_limit=8986179
2020-05-13 11:25.05 transaction cost               eth=0.0126544001208377035 ETH gas=548997 gas_price=4.84E-8 ETH
2020-05-13 11:25.05 Best exchange rate found at Kyber: 0.00527266671701571 ETH / DAI
2020-05-13 11:25.05 Trying to acquire 2 DAI at this rate
2020-05-13 11:25.06 Estimated cost: 0.0392 ETH
2020-05-13 11:25.07 transaction hash: 0x27e005c976d428c9da25ccbf8439f777b8ecbd6ab395acbc93fe59973dedb9c4
2020-05-13 11:25.33 Swap complete. 2 DAI available
2020-05-13 11:25.33 Actual costs: 0.031866087086868504 ETH
ERROR:tornado.application:Uncaught exception GET /ws (::1)
HTTPServerRequest(protocol='http', host='localhost:1994', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/konrad/.virtualenvs/raiden-wizard/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/konrad/Projects/raiden-wizard/raiden_installer/web.py", line 134, in on_message
    return action and action(**data)
  File "/home/konrad/Projects/raiden-wizard/raiden_installer/web.py", line 346, in _run_swap
    raise Exception
Exception
```

Webinterface hangs on spinner.

**Comment by fredo** [comment]
This is already fixed if you use the latest commits
